### ISSUE TITLE
New Purchase API in 2.1.0 apparently not compatible with visionOS

### ISSUE THREAD

**Issue by mattcorey** [TelemetryDeck/SwiftSDK#157]
I've updated to the new Purchase and Error API in 2.1.0, and I'm getting an error when creating a visionOS build - apparently 'storefrontCountryCode' is not supported 🤯

<img width="1120" alt="image" src="https://github.com/TelemetryDeck/SwiftSDK/assets/6993525/3516aa3e-866b-416a-8268-6cc8410e200e">

**Comment by Jeehut** [comment]
@mattcorey Oh yeah, I was surprised when I saw this as well, I assume because it was only available in the US anyways (and other App Stores aren't online). But I thought I had hard-coded `US` to fix this, it seems I overlooked this and CI didn't catch visionOS. Just fixed this and released [2.1.1](https://github.com/TelemetryDeck/SwiftSDK/releases/tag/2.1.1). Sorry for the inconvenience!
