### ISSUE TITLE
Enable Library Evolution Support

### ISSUE THREAD

**Issue by mpdifran** [TelemetryDeck/SwiftSDK#186]
**Environment:**
Xcode 16.0 (16A242)

**Details**
When I link TelemetryDeck to one of my internal frameworks, I get the following warning:

> Module 'TelemetryDeck' was not compiled with library evolution support; using it means binary compatibility for 'MyFramework' can't be guaranteed

To fix this, you need to enable 

```
BUILD_LIBRARY_FOR_DISTRIBUTION
```

**Comment by Jeehut** [comment]
Hi there! Thank you for reporting this issue. This is a really interesting problem that we haven't encountered before.
When embedding TelemetryDeck in a framework that you distribute to other developers, you're absolutely right that library evolution support would be needed to guarantee binary compatibility. However, enabling this by default would come with some tradeoffs like increased binary size and potential performance impacts that might not be desirable for all our users.
In the short term, you have a few potential options:

You could fork the TelemetryDeck repository and enable library evolution support in your fork by modifying the Package.swift file. We can provide guidance on the necessary changes if you'd like to go this route.
We could create a separate branch with library evolution support enabled, which you could reference directly in your Package.swift. This might be a good interim solution while we figure out the best long-term approach.

I've tagged @winsmith (Daniel Jilg, our lead developer) to discuss our options, including:

Creating and maintaining a binary-compatibility branch
Possibly providing an XCFramework distribution in the future
Evaluating how many of our users need this capability

Would you mind sharing a bit more about your use case? It would help us understand how common this need might be among our users and guide our approach to supporting this requirement.
Let us know which option you'd prefer to move forward with, and we'll help you get it set up!

**Comment by mpdifran** [comment]
I use an internal umbrella framework to link all my swift packages to in order to share these dependencies between the main app and app extensions.

App        App Extension
 |              |
 |             /  
 v           v
 Umbrella Framework (linked dynamically)
 |              |              |
 v             v             v
 Various Swift Packages (linked statically)

**Comment by Jeehut** [comment]
Thank you for explaining your use case! The warning can actually be safely ignored, and according to [Swift's official blog post](https://www.swift.org/blog/library-evolution/#when-to-enable-library-evolution-support) about Library Evolution, you should not enable library evolution support in your case since your umbrella framework is "built and distributed together" with your app and extensions. The blog explicitly states:

> Frameworks that are always built and distributed together, such as Swift Package Manager packages or binary frameworks that are **internal to your app**, should **not** be built with library evolution support.

Library evolution is only meant for frameworks that will be built and updated separately from their clients, which isn't the case in your setup. According to the post, library evolution is turned off by default, so I wonder why you turned it on in the first place? Or did I misunderstand your use case?

Let me know if you have any further questions.

**Comment by mpdifran** [comment]
Ah that's good to know. This is a warning that popped up for me in the latest version of Xcode, so some default preference must have changed.

We're probably good to close this then.
