### ISSUE TITLE
Possible Issue with Test Mode detection

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/SwiftSDK#204]
A customer writes

> Hello! I just subscribed to test your tool. By using the SwiftSDK 2.5.0 on an iOS project, data seems to be captured in Live mode when running through the Xcode's simulator (no matter if the scheme is set to debug or release, iOS 17.5 if helps). Not quite sure if this is a bug or just misconfiguration.
> 
> The only code I've added is the initialization, and then call an event from some other view. On the website data is tracked correctly but in live, not in test mode.

```swift
let configuration = TelemetryManagerConfiguration(appID: "my app id here")
TelemetryDeck.initialize(config: configuration)


// somewhere else

TelemetryDeck.signal(source, parameters: ["some key" : "some value"], floatValue: nil, customUserID: nil)
```

Please investigate if this is a bug in the SDK

**Comment by Jeehut** [comment]
@winsmith I've been using SwiftSDK 2.5.0 for a while in various situations and never had this issue. I just double-checked it and can confirm signals are not sent to the live environment but to the test environment. See this screenshot of the Pirate Metrics sample project which was only used in DEBUG mode so far, there are no signals in the live environment:
<img width="973" alt="Screenshot 2024-11-26 at 19 21 31" src="https://github.com/user-attachments/assets/46326571-2c78-4077-b43f-e2965556eb8b">

The most likely cause if a user is experiencing this issue is the DEBUG flag not being set correctly. You could tell them to check:

1. The "Swift Compiler - Custom Flags" and "Active Compilation Conditions" in their build settings
2. Verify "DEBUG" is listed under the Debug configuration for both your main target and any framework targets

They can quickly verify this by adding some debug logging:

```swift
#if DEBUG
    print("Running in DEBUG mode")
    return true
#else
    print("Running in RELEASE mode") 
    return false
#endif
```

Let me know if you want me to make additional checks, but I can't find an issue with the test mode detection.
